
export const ServiceConstants = {
GET_ALL_SERVICE : 'GET_ALL_SERVICE',
EXEC_SERVICE : 'EXEC_SERVICE',
REFRESH_RESULT  : 'REFRESH_RESULT',
SET_SERVICE_EDIT : 'SET_SERVICE_EDIT'
}
export const UserConstants = {
 ACTION_LOGIN : 'ACTION_LOGIN',
 ACTION_SIGNUP : 'ACTION_SIGNUP',
 QUERY_ALL:'QUERY_ALL'
}
export const DashboardCountConstants = {
    COLLECTION_LOGS : 'COLLECTION_LOGS',
    GENERAL:'GENERAL',
    ATTACK_WEB : 'COUNT_ATTACK_WEB',
    OPERATIONS : 'COUNT_OPERATIONS',
    VULNERABILITY: 'COUNT_VULNERABILITY',
    WARRING:'COUNT_WARNING',
    VIOLATE:'COUNT_VIOLATE'
}
export const NewsConstants = {
    FEATURED_NEWS:'FEATURED_NEWS'
}
export const SettingsConstants = {
    CONFIG:'CONFIG'
}
export const LAYOUTCONSTANTS = {
    LOADING : 'LOADING'
   }
export const CalendarConstant = {
    GET_DATA_SCHEDULE : 'GET_DATA_SCHEDULE'
}
export const HistoryConstant = {
    GET_ALL_HISTORY : 'GET_ALL_PHISTORY'
}
export const ClassConstant = {
    GET_ALL_CLASS : 'GET_ALL_CLASS',
    ADD_CLASS: 'ADD_CLASS',
    UPDATE_CLASS:'UPDATE_CLASS',
    REMOVE_CLASS:'REMOVE_CLASS',
    ASSIGN_PROFESSOR:'ASSIGN_PROFESSOR',
    ADD_MEMBER:'ADD_MEMBER',
    GET_DATA_CHART:'GET_DATA_CHART'
}
export const ProfessorConstant = {
    GET_ALL_PROFESSOR : 'GET_ALL_PROFESSOR',
    ADD_PROFESSOR: 'ADD_PROFESSOR',
    UPDATE_PROFESSOR:'UPDATE_PROFESSOR',
    REMOVE_PROFESSOR:'REMOVE_PROFESSOR',
    CHANGE_AVATAR_PROFESSOR:'CHANGE_AVATAR_PROFESSOR'
}