
export const UserConstants = {
  ACTION_LOGIN: "ACTION_LOGIN",
  ACTION_SIGNUP: "ACTION_SIGNUP",
  QUERY_ALL: "QUERY_ALL",
};
export const DashboardCountConstants = {
  COLLECTION_LOGS: "COLLECTION_LOGS",
  GENERAL: "GENERAL",
  ATTACK_WEB: "COUNT_ATTACK_WEB",
  OPERATIONS: "COUNT_OPERATIONS",
  VULNERABILITY: "COUNT_VULNERABILITY",
  WARRING: "COUNT_WARNING",
  VIOLATE: "COUNT_VIOLATE",
};
export const SettingsConstants = {
  CONFIG: "CONFIG",
};
export const LAYOUTCONSTANTS = {
  LOADING: "LOADING",
};
export const CalendarConstant = {
  GET_DATA_SCHEDULE: "GET_DATA_SCHEDULE",
};
export const HistoryConstant = {
  GET_ALL_HISTORY: "GET_ALL_PHISTORY",
  ADD_HISTORY: "ADD_HISTORY",
  REMOVE_HISTORY: "REMOVE_HISTORY",
  UPDATE_HISTORY: "UPDATE_HISTORY",
};
export const ClassConstant = {
  GET_ALL_CLASS: "GET_ALL_CLASS",
  ADD_CLASS: "ADD_CLASS",
  UPDATE_CLASS: "UPDATE_CLASS",
  REMOVE_CLASS: "REMOVE_CLASS",
  ASSIGN_PROFESSOR: "ASSIGN_PROFESSOR",
  ADD_MEMBER: "ADD_MEMBER",
  GET_DATA_CHART: "GET_DATA_CHART",
};
export const ProfessorConstant = {
  GET_ALL_PROFESSOR: "GET_ALL_PROFESSOR",
  ADD_PROFESSOR: "ADD_PROFESSOR",
  UPDATE_PROFESSOR: "UPDATE_PROFESSOR",
  REMOVE_PROFESSOR: "REMOVE_PROFESSOR",
  CHANGE_AVATAR_PROFESSOR: "CHANGE_AVATAR_PROFESSOR",
};
export const StudentConstant = {
  GET_ALL_STUDENT: "GET_ALL_STUDENT",
  ADD_STUDENT: "ADD_STUDENT",
  REMOVE_STUDENT: "REMOVE_STUDENT",
  UPDATE_STUDENT: "UPDATE_STUDENT",
  GRADE_MARK: "GRADE_MARK",
  UPDATE_NARK: "UPDATE_NARK",
  DETAIL_STUDENT: "DETAIL_STUDENT",
  CHANGE_AVATAR_STUDENT: "CHANGE_AVATAR_STUDENT",
};
export const SubjectConstant = {
  GET_ALL_SUBJECT: "GET_ALL_SUBJECT",
  ADD_SUBJECT: "ADD_SUBJECT",
  REMOVE_SUBJECT: "REMOVE_SUBJECT",
  UPDATE_SUBJECT: "UPDATE_SUBJECT",
};
export const DocumentConstant = {
  GET_ALL_DOCUMENT: "GET_ALL_DOCUMENT",
  ADD_DOCUMENT: "ADD_DOCUMENT",
  REMOVE_DOCUMENT: "REMOVE_DOCUMENT",
  UPDATE_DOCUMENT: "UPDATE_DOCUMENT",
};
export const MessageConstant = {
  GET_DATA_MESSAGE:"GET_DATA_MESSAGE",
  ADD_MESSAGE:"ADD_MESSAGE"
}
